name: release

on:
  push:
    tags:
      - v*

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - run: echo "VERSION=$(npm version --json|jq .graphql -r)" >> $GITHUB_ENV

      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          context: ./
          tags: ghcr.io/bangumi/graphql:${{ env.VERSION }},ghcr.io/bangumi/graphql:latest
